// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"github.com/swaggo/swag"
)

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Title:       "Go API",
	Description: "API para cadastro e login de usuários.",
	Version:     "1.0",
}

func init() {
	// Registrar a especificação Swagger diretamente.
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
